/* AUTO-GENERATED by scripts/generate-team-photos.mjs — do not edit by hand.
   Regenerate with: node scripts/generate-team-photos.mjs */
import type { TeamPhoto } from "@/content/team";

export const teamPhotos: Record<string, TeamPhoto> = {
  "muhammad-shahid": {
    src: "/images/team/muhammad-shahid.webp",
    width: 480,
    height: 480,
    blurDataURL: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4WAoAAAAQAAAAFwAAFwAAQUxQSAoAAAABB9D+iAhERP8DVlA4IEQAAACQAwCdASoYABgAPu1ur1KppiQnqAgBMB2JYwC/Z8CBP3FSlFVAAP7u4aohcQg3VTOI+p7Sg8GPXAySiVSAJXkhagAAAA==",
  },
  "zaman-ali": {
    src: "/images/team/zaman-ali.webp",
    width: 480,
    height: 480,
    blurDataURL: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4WAoAAAAQAAAAFwAAFwAAQUxQSAoAAAABB9D+iAhERP8DVlA4IEAAAABQAwCdASoYABgAPu1wsFIppiSjqAgBMB2JZQC2yBdycwgO4AD+7rSxNWRN9IDObvaaARuiB8/1gjSrCAvbQAAA",
  },
  "muhammad-abiid": {
    src: "/images/team/muhammad-abiid.webp",
    width: 480,
    height: 480,
    blurDataURL: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4WAoAAAAQAAAAFwAAFwAAQUxQSAoAAAABB9D+iAhERP8DVlA4IDoAAAAQAwCdASoYABgAPu1wsFKppiSjqAgBMB2JZQDE2Bi5qiAA/u7hao0zbLRSNo+d3axWBzUuEvMT4AAA",
  },
};
